### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by fwouts** [chen0040/js-graph-algorithms#1]
Hi and thank you for creating this library!

Would you be open to adding TypeScript definitions? Here's a first attempt: https://github.com/fwouts/js-graph-algorithms/blob/master/src/jsgraphs.d.ts.

Otherwise I'm happy to submit it separately to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by chen0040** [comment]
Hi @fwouts Many thanks for the effort in creating the TypeScript definition! I am happy to add the typescript definition. Could you create a pull request so that i can merge the typescript definition to the master?

**Comment by chen0040** [comment]
Also could u change the namespace in the typescript to something like JsGraphs instead of Jss?
