### ISSUE TITLE
Ford Fulkerson issue

### ISSUE THREAD

**Issue by mathis24** [chen0040/js-graph-algorithms#4]
Hi,

  Thanks a lot for this very well-written code about graphs. I used FordFulkerson and something went wrong in some cases. 
 In the FordFulkerson function, I was wondering if the loops (twice the same)
for(var x = this.t; x != this.s; x = this.edgeTo[x].from()) { 
shouldn't be replaced by:
for(var x = this.t; x != this.s; x = this.edgeTo[x].other(x)) {    // other instead of from 

Regards,

**Comment by chen0040** [comment]
Hi @mathis24 , many thanks for the uncovering the issue and suggesting the fix, yes you are right about the for loop may be causing the problem, i have incorporated your suggested fix into the codes and submit a version update to npmjs :)

**Comment by mathis24** [comment]
Thank you very much @chen0040 !
